### ISSUE TITLE
Add related-content suggestions

### ISSUE THREAD

**Issue by xaprb** [xaprb/story#17]
I removed related posts and I want to add them back. 

By default the related content just picks the top N most relevant related items. If you browse from related -> related -> related, you'll end up just going back in history to obscure old posts. 

The problem is, if you remove the default limitation that just shows "older" posts, you end up stuck in a local set of posts that are a tight cycle and you don't get out of it.

I'd like to switch the related config to let it display newer, but then pick, say, the most relevant 10, and then pick a random-but-deterministic 3 out of them to display. Perhaps by hashing. So each post will show a specific 3 of the most 10 relevant in the "local maximum" set of related posts, and you'll browse around amongst a related, but not-boring and not-spiral-of-death related content. Ultimately, these 10 posts probably all, taken together, show a cluster of all 10 related content that is kind of a local maximum trap too, but it's less obviously perceptible to a user.

Ultimately I'd like to add a step to use e.g. K-Means Clustering to actually generate better quality related content suggestions.

**Comment by xaprb** [comment]
Thanks! I'm going to add a couple of other links I've pulled together here...

- https://www.scribd.com/doc/89373376/K-Means-Pseudocode
- http://tech.reputation.com/improving-topic-identification-k-means-clustering/
- https://www.intercom.com/blog/machine-learning-way-easier-than-it-looks/
- https://github.com/bbalet/stopwords
- http://matpalm.com/resemblance/simhash/
- https://github.com/bbalet/gorelated
- https://github.com/reiver/go-porterstemmer
- https://github.com/xaprb/cluster-text (it's slower than it should be)

**Comment by xaprb** [comment]
It's potentially possible to use the Lunr search index to do this in JavaScript rather than with Hugo.

**Comment by Sach97** [comment]
You are right it is possible to use [similarity(otherVector) → {Number}](https://lunrjs.com/docs/lunr.Vector.html ) from Lunr.

**Comment by xaprb** [comment]
From #50:

> Listing related posts as "Related" or "See also" at the end of the post, increases user traction. May be we should have [Related Content](https://gohugo.io/content-management/related/) in Story?  
> 
> I am thinking more like [BeautifulHugo](https://themes.gohugo.io//theme/beautifulhugo/post/2017-03-20-photoswipe-gallery-sample/) or [min_night](https://themes.gohugo.io//theme/min_night/2014/04/02/getting-started-with-hugo/)

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
