### ISSUE TITLE
Support an author footer

### ISSUE THREAD

**Issue by xaprb** [xaprb/story#33]
Add a footer to individual post pages (`single.html`) that is a template block that's empty by default, and a user can add their custom content. Perhaps could use the system described in https://www.netlify.com/blog/2018/07/24/hugo-tips-how-to-create-author-pages/ but I think that's overkill: a simplifying design decision is that "story" is a theme for a single author, not multiple authors.

Design inspiration:

<img width="969" alt="screen shot 2018-08-09 at 5 37 00 pm" src="https://user-images.githubusercontent.com/279875/43927317-1d18d712-9bfb-11e8-9017-c9b1acba7bec.png">

**Comment by xaprb** [comment]
Fixed in 745fe6191fed818bddd7d9a68d09dbc2645d3c8e

**Comment by alfieqashwa** [comment]
there's NO author's footer below of every post's pages on the demo.

**Comment by xaprb** [comment]
I cannot reproduce what you are reporting.

<img width="943" alt="screen shot 2019-01-04 at 8 42 44 am" src="https://user-images.githubusercontent.com/279875/50690849-dc143d80-0ffc-11e9-8637-08284abeda49.png">
