### ISSUE TITLE
Add table of contents or index

### ISSUE THREAD

**Issue by tve** [xaprb/story#43]
Your theme looks fabulous but the one thing I'm really missing is some succinct index of posts. Looking at your own site, you now have 61 pages of posts. That means that posts past the first page (or two) are essentially invisible. Yeah, maybe a search leads someone to one, but it's really difficult to browse what else you've written. Have you had thoughts about a solution? Or perhaps there is already a solution and I just haven't found it yet?

**Comment by xaprb** [comment]
I don't have a good answer for this. Continuing with my own site as an example, 1200+ pages of content isn't easy to organize. I don't know how to give a succinct overview of 1200 anything :-/

**Comment by rootkea** [comment]
#49 should achieve this. What do you think?
