### ISSUE TITLE
[Feature Request] Table of Contents

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#46]
Hello!

I'm new to (Hu)Go and just tried story theme and I really like it!  

Often at times, when the technical article gets some considerable length it becomes cumbersome to jump around the article. It would be really cool if we could have the  table of contents beside the post.  

I'm mainly looking at the one provided by AllinOne theme.[0]  
Even the one from er theme looks nice too.[1]  

[0] https://orianna-zzo.github.io/AllinOne-html/blog/2018-08/%E9%9F%B3%E4%B9%90%E5%89%A7catrepo/ 
[1] https://themes.gohugo.io//theme/er/post/markdown-syntax/

**Comment by xaprb** [comment]
Hi, since you opened #49 which is similar, I think we should continue the discussion there.

**Comment by rootkea** [comment]
Umm.. #49 is about the "archives" page while this issue is about the [Table of Contents (ToC)](https://gohugo.io/content-management/toc) of a particular post.  

Please take a look at these [AllinOne](https://themes.gohugo.io//theme/AllinOne/blog/2018-08/%E9%9F%B3%E4%B9%90%E5%89%A7catrepo/) and [er](https://themes.gohugo.io//theme/er/post/migrate-from-jekyll/) examples.

**Comment by xaprb** [comment]
My mistake, thanks for catching that.

**Comment by tchinchow** [comment]
Hello,

This message is merely for the sake of curation : I'm just gathering pointers in case someone looks into this feature request.

From the links that @rootkea provides, I can read that [ER Hugo template](https://github.com/lingxz/er) uses [tocbot](https://github.com/tscanlin/tocbot). This is probably no longer necessary and therfore not a good idea.

Indeed Hugo now has its [own mechanism](https://gohugo.io/content-management/toc/)...
... and it seems that it can be [extensively configured](https://gohugo.io/getting-started/configuration-markup/#table-of-contents).

> **Note**:
>
> I tried Hugo's builtin method very quickly with Story and it works indeed _(hugo v0.68.3)_.
>
> I believe that it's now just a matter of writing the right HTML+CSS on blog posts.
> I suppose this could be enabled globally or locally through Story's
> [feature](https://story.xaprb.com/features/) mechanism.
>
> Maybe I'll give it a try if I find some time.

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
