### ISSUE TITLE
[Feature Request] Reading Time

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#47]
Hello!  

It would be cool to display the Reading time (page variable) on homepage in post snippet and on post page. Prompts like "2 minute reading time" helps the user to make the decision of whether to read or not.   

I'm thinking about the one like in type theme[0][1]  

[0] https://themes.gohugo.io//theme/type/  
[1] https://themes.gohugo.io//theme/type/post/migrate-from-jekyll/

**Comment by xaprb** [comment]
I considered this but opted not to. My old theme used to have this. Let's see if anyone else wants to vote for this. We could always add it with a flag to enable/disable it.

**Comment by rootkea** [comment]
> It would be cool to display the Reading time (page variable) on homepage in post snippet

To explain further, I would like to draw your attention to the Medium, one of the most popular blogging platforms.

![medium](https://user-images.githubusercontent.com/2694559/49941368-2ca2ea00-feda-11e8-8123-6694b4d2d512.png)

Thanks!

**Comment by xaprb** [comment]
To set expectations clearly, I do not plan to work on this, but I will accept a pull request as long as it uses a feature flag and works correctly in all important scenarios, e.g. responsive layout at different screen sizes.

**Comment by xaprb** [comment]
I see value in this for attracting potential readers to the content, for example the way Slack previews give people enough information to decide whether they want to follow a link:

<img width="387" alt="screen shot 2019-01-16 at 9 15 05 am" src="https://user-images.githubusercontent.com/279875/51254497-4323e180-196f-11e9-85b2-31d8cb3bf0e3.png">

The meta headers appear to be:

    <meta name="twitter:label1" value="Reading time"><meta name="twitter:data1" value="5 min read">

I would also consider adding this to the unobtrusive article metadata in the list view, e.g. on mouseover,

<img width="974" alt="screen shot 2019-01-16 at 9 20 04 am" src="https://user-images.githubusercontent.com/279875/51254848-f12f8b80-196f-11e9-8a24-3c05d2d5b1c4.png">

**Comment by alihusnainarshad** [comment]
I will  highly appreciate this feature. Please @xaprb  .
