### ISSUE TITLE
Malformed URLs when using Hugo's "relativeurls" feature

### ISSUE THREAD

**Issue by tchinchow** [xaprb/story#48]
The following configuration in the 'config.toml' file fails producing a valid site in 'public'.
```
baseurl = ""
relativeurls = true
```

URLs are built relative to the articles and NOT to the site's base URL.

I figured out that all images, css and other references must be set with a leading '/' in all the "partials" "singles", "lists" and other html templates before calling "absURL".

**Comment by tchinchow** [comment]
_I have created a github account, forked the original project, and will hopefully propose a pull-request soon._

**Comment by xaprb** [comment]
I'm not sure this is a bug, please check https://github.com/gohugoio/hugoThemes/issues/417 and see if the behavior you're seeing is a consequence of the changes I had to make to include this theme in the Hugo theme directory.

**Comment by tchinchow** [comment]
I missed https://github.com/gohugoio/hugoThemes/issues/417. Thanx for sharing. It opened my eyes on the possibility to host the site in a subfolder of a server and not necessarily on the root, which obsoletes the fix I was hoping to push.

I'm still having issues with absURL... And I'm confused !
Sorry about the long post : I just need to demonstrate what I've tried based on https://discourse.gohugo.io/t/gohugo-without-baseurl-or-with-relative-url-only/2779.

Other people seem to struggle with `absURL` v.s. `relURL`: https://discourse.gohugo.io/t/canonifyurls-relativeurls-interaction/5448/2

I'm not sure if @onedrawingperday will read this and would find some time to help clarifying how `absURL` works ?

No matter the angle: it it's always wrong! Could this be a bug with Hugo ?

Here's what I tried:
With the following site config:
```
# Site settings
# baseurl = "https://example.com/public"
# canonifyURLs = true
relativeURLs = true
```
`{{ "/css/story.css" | absURL }}` transforms to
- `./css/story.css` in `public/index.html`
- `../css/story.css` in `public/about-story/index.html`
**GOOD** relativeURLs works well...

`{{ "css/story.css" | absURL }}` gives
- `css/story.css` in `public/index.html`
- `css/story.css` in `public/about-story/index.html`
**WRONG**: Both URL are built relative to the current folder but pages live in different folders !!!

now, with
```
# Site settings
baseurl = "https://example.com/public"
# canonifyURLs = true
# relativeURLs = true
```
`{{ "/css/story.css" | absURL }}` transforms to
- `https://example.com/css/story.css` in `public/index.html`
- `https://example.com/css/story.css` in `public/about-story/index.html`
**WRONG**: I fail to understand what `/css/` is "relative" to as suggested earlier by @onedrawingperday in https://github.com/gohugoio/hugoThemes/issues/417... It seems to me that both URLs are absolute to the site's root _(and not the `/public` folder)_.

`{{ "css/story.css" | absURL }}` gives
- `https://example.com/public/css/story.css` in `public/index.html`
- `https://example.com/public/css/story.css` in `public/about-story/index.html`
**GOOD**: This is todays behaviour in the story theme.

I'll live with my buggy patch for now and will keep digging or posting questions around.
If I find a universal way of doing it then I'll push a pull-request.

Many Thanx for the theme _(which is awesome)_ and for your time.

**Comment by xaprb** [comment]
Thanks @tchinchow! My guess is that the relative URL features in Hugo don't always work well with all combinations of things. I think that's probably why the Hugo authors are using absURL for hosting the theme demo sites. I would say the safest bet is to mimic that; which is what your last example does, using `baseurl = "https://example.com/public"` and no leading slashes on URLs. For what it's worth, I had to remove leading slashes from URLs to make the theme work right in the demo site as in the above-linked issue, so it seems like that's probably the way to build your site, too, not just the best way to do the theme itself. I hope this helps!

If you want more general help with this, by the way, I would use the Hugo forums: https://discourse.gohugo.io/

**Comment by tchinchow** [comment]
yes well... "it's complicated"...

Oddly enough:
```
baseurl = "/"
relativeURLs = true
```
produces true relative URLs _(i.e. `./` and `../`)_ for the css and javascript...
... yet it fails with images although they are also piped through `absURL` exactly as javascript is.

Hope this info can help some folks...

sorry about the false bug-report.
