### ISSUE TITLE
[Feature Request] Archives

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#49]
Hello!

Besides tags and categories, Archives is one of the best way to browse any blog. It would be really cool to have the "Archives" page in Story.  

By Archives page I mean the page where posts titles (with minimal info attched) are listed chronologically.  

Here are some of the example Archive pages. Please have a look.  
1. https://themes.gohugo.io/theme/hugo-theme-even/post/  
2. https://themes.gohugo.io/theme/er/post  
3. https://themes.gohugo.io/theme/hugo-kiera/posts/  
4. https://themes.gohugo.io//theme/hugo-theme-cactus-plus/posts  

Thanks!

**Comment by xaprb** [comment]
That seems like a good feature to add. I would note that some of the items you referenced have pagination in their archives, which doesn't seem desirable to me. The current layout of Story has pretty minimalistic listing pages, with pagination. My blog has 20 items per page and there are 62 such pages of listings. An archive would only be an improvement if it had all items on a single page, in my opinion.

**Comment by xaprb** [comment]
Adding a screenshot for future reference, of what a reasonable design might look like...

<img width="788" alt="screen shot 2018-11-29 at 4 54 18 pm" src="https://user-images.githubusercontent.com/279875/49254679-d4f38180-f3f7-11e8-8a35-8801bb72da69.png">

**Comment by rootkea** [comment]
> An archive would only be an improvement if it had all items on a single page, in my opinion.

I completely agree. And that's exactly why I would like to suggest the attached archives design used by [Blogger.com](https://tahmidmc.blogspot.com/2013/01/using-high-low-side-driver-ir2110-with.html).  

![archives](https://user-images.githubusercontent.com/2694559/49287161-5f89be80-f494-11e8-805f-31c250889ff2.png)

**Comment by xaprb** [comment]
https://story.xaprb.com/archives/

**Comment by now-im** [comment]
How to add this to the hugo project?
