### ISSUE TITLE
Taxonomy Terms template missing

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#52]
Currently `story` doesn't have dedicated taxonomy terms template. This makes tags (\<base-url\>/tags) and categories (\<base-url\>/categories) pages to display tags/categories terms exactly as that of posts which doesn't feel right.
![tags](https://user-images.githubusercontent.com/2694559/49327880-d2f80280-f55e-11e8-8163-2223c1bbd665.png)

Here are few taxonomy terms pages for reference:

1. [Er](https://themes.gohugo.io/theme/er/tags)  
![er-tags](https://user-images.githubusercontent.com/2694559/49327905-6598a180-f55f-11e8-9760-08005ebaf468.png)

2. [BeautifulHugo](https://themes.gohugo.io/theme/beautifulhugo/tags)
![beautifulhugo-1](https://user-images.githubusercontent.com/2694559/49327963-4bab8e80-f560-11e8-86ca-f3222daae5f6.png)
On click-expand:
![beautifulhugo-2](https://user-images.githubusercontent.com/2694559/49327967-55cd8d00-f560-11e8-95ed-3541d19b5cbd.png)

3. [Kiera](https://themes.gohugo.io/theme/hugo-kiera/tags)
![kiera-tags](https://user-images.githubusercontent.com/2694559/49327921-a1cc0200-f55f-11e8-9989-d2a551706950.png)

**Comment by rootkea** [comment]
I went through the Hugo [docs](https://gohugo.io/templates/taxonomy-templates) and composed `layouts/_default/terms.html` as follows:  

    {{ define "main" }}
        {{ .Content }}
        <ul>
        {{ $type := .Type }}
        {{ range $key, $value := .Data.Terms.ByCount }}
            {{ $name := .Name }}
            {{ $count := .Count }}
            {{ with $.Site.GetPage (printf "/%s/%s" $type $name) }}
                <li><a href="{{ .Permalink }}">{{ $name }}</a> {{ $count }}</li>
            {{ end }}
        {{ end }}
        </ul>
    {{ end }}

This yielded a simple tags terms list sorted by popularity.  
![story-tags](https://user-images.githubusercontent.com/2694559/49328065-f7091300-f561-11e8-9e2b-c393592fa257.png)

Thought this might help. :)

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
