### ISSUE TITLE
Move timestamp to post snippet

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#57]
At present, the post timestamp is hidden and only gets revealed if the cursor is hovered over the thumbnail (It seems user is supposed to know/find this on their own ;))
![story](https://user-images.githubusercontent.com/2694559/49941096-63c4cb80-fed9-11e8-972d-29640c9f4504.png)
Taking a cue from Medium, an one of the most popular blogging platforms out there, I would like to suggest to move the timestamp in page snippet (after the summary part)
![medium](https://user-images.githubusercontent.com/2694559/49941210-c322db80-fed9-11e8-9f2d-13820c9a00db.png)

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
