### ISSUE TITLE
Remove "Continue Reading" from post snippet

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#58]
Hello!

In the spirit of simplicity and minimalism I would like to suggest removing the "Continue Reading" from the post snippet on list page.

![story](https://user-images.githubusercontent.com/2694559/49941936-d171f700-fedb-11e8-86bb-88a423c4d524.png)

Instead, I propose that the post summary should be a link to post permalink, exactly like the thumbnail and post title.

Similar thoughts follow for "View Slideshow" and "Talk Details".

**Comment by out-of-order** [comment]
Same thought on simplicity.
I don't see any need for the button while title and thumbnail both are reffering to post

**Comment by xaprb** [comment]
I see it differently, as a call to action (CTA) that invites reading and makes it obvious where to click/touch. However I agree that this is a matter of opinion. I'd approve a pull request that leaves the call to action enabled by default, but adds a [feature flag](https://story.xaprb.com/features/) to disable it. A good name for the feature might be something like `reading-cta` or something.

**Comment by out-of-order** [comment]
Great idea if it can be done that way!

**Comment by xaprb** [comment]
Just to set expectations clearly, I'll accept a pull request for this but I don't plan to work on it myself.

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
