### ISSUE TITLE
Vscode error in /themes/story/layouts/_default/search.html

### ISSUE THREAD

**Issue by now-im** [xaprb/story#60]
I am no coder. I am currently trying to apply your themes on my hugo page. So, far not so good as this project is very complex. My Vscode editor is constantly giving me the error in one of your files.
The concerned code of lines are:
```
			 $.getJSON("{{ "index.json" | absURL }}")
```
The Vscode errors are the following:
```
{
	"resource": "/themes/story/layouts/_default/search.html",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "',' expected.",
	"source": "js",
	"startLineNumber": 33,
	"startColumn": 20,
	"endLineNumber": 33,
	"endColumn": 25
}
```
and 

```
{
	"resource": "/themes/story/layouts/_default/search.html",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "',' expected.",
	"source": "js",
	"startLineNumber": 33,
	"startColumn": 30,
	"endLineNumber": 33,
	"endColumn": 44
}
```
If this is a non issue close it down. Thanks for reading.

**Comment by now-im** [comment]
Another thing. I can't change default-header-img.jpg in the themes/story/static/img/ folder. Whenever I change it turns back to the default image.

**Comment by xaprb** [comment]
I don't know anything about VSCode. You can change the image with the instructions in the section "Header Images" on https://story.xaprb.com/images/

**Comment by now-im** [comment]
Thanks a lot. One last help, please. I would like to remove the rss feed icon and rename the Slide option in the upper right to Blog which will list all the blog I have written. Any solution?

**Comment by now-im** [comment]
I really appreciate that you have made this awesome product open source. I could not have afforded it. Lots of wishes for you my friend.

**Comment by xaprb** [comment]
You're welcome, and thank you so much for the kind words. It really means a lot to me ❤️
