### ISSUE TITLE
New Menu entries and RSS/Search icons

### ISSUE THREAD

**Issue by out-of-order** [xaprb/story#62]
When I create new directories and menu entries in config.toml, the RSS and Search icons disappear when entering one of these lists.
Do I have to create new sections for each menu entry like it is for talks and slides in partials/li.html ?

{{- if eq .Section "talks" }}

**Comment by xaprb** [comment]
I'm sorry but I don't understand this issue report.

**Comment by out-of-order** [comment]
I try again:
If I add a new main menu entry in config.toml and then enter this list, the icons for RSS and Search don't show up.

**Comment by xaprb** [comment]
I'm still confused. Can you add a screenshot and link to your site's config.toml, or provide its contents as a code listing or gist?
