### ISSUE TITLE
htmlEscaped chars in json output for lunr

### ISSUE THREAD

**Issue by acahir** [xaprb/story#71]
**Describe the bug**
Encoding artifacts are present in Lunr's search results. I believe it's escaped html chars from the .Title page variable used in index.json. Same potential problem with .Summary.

**To Reproduce**
1. Go to https://themes.gohugo.io/theme/story/search/
2. Search for 'music'
3. Look at first result

**Expected behavior**
A non-mangled string

**Additional context**
htmlUnescaping the output from .Title and .Summary seems to fix the problem. `(.Summary | plainify | htmlUnescape )`

**Comment by xaprb** [comment]
Fixed in #72, thanks!
