### ISSUE TITLE
[FEATURE] Configurable fonts

### ISSUE THREAD

**Issue by whizz** [xaprb/story#82]
Unfortunately, the Quattrocento and Quattrocento Sans fonts, though beautiful, do not support all Eastern European characters (for example ř and ě). Because the fonts are hardcoded, I had to fork story and change it to something else, which supports the character set I need. I replaced Quattrocento with Spectral and Quattrocento Sans with Roboto (not too happy with that one, but did not have time to look for something prettier).

So there are two solutions basically.  Either use different fonts altogether, which have better support for non-English characters--but I guess you picked the fonts for a reason. Or make the fonts configurable. I guess making it configurable would be better. 

If you are OK with that, I will put together a PR. Any other ideas how to solve the issue are welcome, of course.

**Comment by xaprb** [comment]
I'm OK with configurable and would welcome a PR. My thought is to create an array in the site config, listing font URLs to load from Google Fonts, and then to put *all* the fonts into the CSS files in the font stack. Whichever one the user wants will get loaded via the URL, so it should "just work." Maybe?

**Comment by andreimoustache** [comment]
The fonts not supporting other languages' special characters was my issue as well :'(
Hope the PR above helps

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
