### ISSUE TITLE
[BUG] Post font is too small

### ISSUE THREAD

**Issue by rootkea** [xaprb/story#83]
Before the commit f3a57457d8f508857f24766af36adb8ee9edb7aa:
![Pleasant font](https://user-images.githubusercontent.com/2694559/54752020-864f3a80-4bd4-11e9-87ef-96cb296c19be.png)
A pleasant buttery text!

But now, after the said commit:
![new](https://user-images.githubusercontent.com/2694559/54752054-a54dcc80-4bd4-11e9-9e10-05d6c4aeef7d.png)
Very small text size.

Is this intentional?

OS: Debian 9
Browser: Firefox Developer Edition 67.0b3 (64-bit)

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
