### ISSUE TITLE
Add a menu

### ISSUE THREAD

**Issue by xaprb** [xaprb/story#9]
The layout is a bit too minimalistic at the moment. I'd like to add a hamburger menu icon at the top, which would make it easier to access features such as search. The "lanyon" Hugo theme I used to use had one that worked well. Several of the HTML5 Up themes have these as well, such as [this one](https://html5up.net/uploads/demos/editorial/index.html), and that could be easier to port because they're based on a common underlying theme framework called Skel.

**Comment by xaprb** [comment]
Fixed

**Comment by out-of-order** [comment]
I would like to use a hamburger icon.
Do you have plans for story to make the menu responsive and collapse?
