### ISSUE TITLE
[BUG] : Columns not vertically aligned when footer used

### ISSUE THREAD

**Issue by rberlind** [xaprb/story#91]
**Describe the bug**
It seems that using a layout slide with `.footer[]` throws off the vertical alignment of the first column in remark slides using the classes `col-2` and `col-3`.

**To Reproduce**
Add a slide to an MD file with Remark slides like this:
```
layout: true

.footer[
- Copyright © 2019 Acme
]
```
and then add a slide like this after it:
```
name: a-2-col-slide
class: col-2
# Title

* bullet 1
* bullet 2
* bullet 3
* bullet 4

Here are more bullets:

* bullet 5
* bullet 6
* bullet 7
* bullet 8
```

**Expected behavior**
The columns should be vertically aligned

**Screenshots**

![Screen Shot 2019-10-28 at 7 53 48 PM](https://user-images.githubusercontent.com/23617012/67726677-05072400-f9bd-11e9-993f-797d921f90d0.png)

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
