### ISSUE TITLE
shortcodes in slides

### ISSUE THREAD

**Issue by geoffreymbrown** [xaprb/story#95]
This isn't exactly a feature or a bug.   I don't seem to be able to use shortcodes in the the slide markdown.  This seems to be due to the passing of RawContent to  remarkjs.  Is there any way around this ?

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
