### ISSUE TITLE
[BUG] page bundles not linking images correctly

### ISSUE THREAD

**Issue by ckoehler** [xaprb/story#99]
**Describe the bug**
My posts are organized as page bundles, with images etc in the same directory. With Story, images are linked from the site root and, since they don't exist there, throw 404s. Other themes (like Pickles) support this.

**To Reproduce**
Create a page bundle with an image somewhere (like content/post/2020/foobar/index.md), set `image: "foo.jpg"`. 

**Expected behavior**
It shows the thumbnail.

**Comment by xaprb** [comment]
I’m sorry but I’m not interested in maintaining this theme anymore. I’m glad it’s been useful, and I encourage someone to continue development elsewhere. The MIT license is very permissive and should not place any burdensome restrictions upon that.
